/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import napakalaki.BadStuff;
/**
 *
 * @author Christian
 */
public class BadStuffView extends javax.swing.JPanel {

     private BadStuff badstuffModel;
    
    /**
     * Creates new form BadStuffView
     */
    public BadStuffView() {
        initComponents();
    }
   
     
public void setBadstuff (BadStuff b) {
    badstuffModel = b;
    
    if (b.getdeath() == true)
        muerto.setText("Yes");
    else
        muerto.setText("No");
    
      nivelesPerdidos.setText(""+b.getLevels());
      tesorosvisiblesPerdidos.setText(""+b.getnVisible());
      tesorosocultosPerdidos.setText(""+b.getnVisible());
      tipotesorosperdidosVisibles.setText(""+b.getVT());
      tipotesorosperdidosOcultos.setText(""+b.getHT());
      
    repaint();
    revalidate();
}
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        TituloNivelesPerdidos = new javax.swing.JLabel();
        TituloMuerto = new javax.swing.JLabel();
        TituloTesorosVisiblesPerdidos = new javax.swing.JLabel();
        TituloTesorosOcultosPerdidos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nivelesPerdidos = new javax.swing.JLabel();
        muerto = new javax.swing.JLabel();
        tesorosvisiblesPerdidos = new javax.swing.JLabel();
        tesorosocultosPerdidos = new javax.swing.JLabel();
        TituloTipoTesoroVisiblePerdido = new javax.swing.JLabel();
        TituloTesoroOcultoPerdido = new javax.swing.JLabel();
        tipotesorosperdidosVisibles = new javax.swing.JLabel();
        tipotesorosperdidosOcultos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jScrollPane1.setViewportView(jEditorPane1);

        setForeground(new java.awt.Color(255, 99, 30));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TituloNivelesPerdidos.setText("Lost levels:");

        TituloMuerto.setText("Are you dead? ");

        TituloTesorosVisiblesPerdidos.setText("Visible lost treasures:");

        TituloTesorosOcultosPerdidos.setText("Hidden lost treasures:");

        nivelesPerdidos.setText("LEVELS");

        muerto.setText("yes/no");

        tesorosvisiblesPerdidos.setText("VLT");

        tesorosocultosPerdidos.setText("HLT");

        TituloTipoTesoroVisiblePerdido.setText("Specific visible lost treasures:");

        TituloTesoroOcultoPerdido.setText("Specific hidden lost treasures:");

        tipotesorosperdidosVisibles.setText("SVLT");

        tipotesorosperdidosOcultos.setText("SHLT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloTesorosVisiblesPerdidos)
                            .addComponent(TituloNivelesPerdidos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TituloTesorosOcultosPerdidos)
                            .addComponent(TituloTesoroOcultoPerdido))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TituloTipoTesoroVisiblePerdido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nivelesPerdidos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tipotesorosperdidosOcultos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(tesorosocultosPerdidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tesorosvisiblesPerdidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipotesorosperdidosVisibles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(TituloMuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(muerto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TituloNivelesPerdidos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nivelesPerdidos))
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(tesorosvisiblesPerdidos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TituloTesorosVisiblesPerdidos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipotesorosperdidosVisibles)
                    .addComponent(TituloTipoTesoroVisiblePerdido, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloTesorosOcultosPerdidos)
                    .addComponent(tesorosocultosPerdidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloTesoroOcultoPerdido)
                    .addComponent(tipotesorosperdidosOcultos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloMuerto)
                    .addComponent(muerto))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloMuerto;
    private javax.swing.JLabel TituloNivelesPerdidos;
    private javax.swing.JLabel TituloTesoroOcultoPerdido;
    private javax.swing.JLabel TituloTesorosOcultosPerdidos;
    private javax.swing.JLabel TituloTesorosVisiblesPerdidos;
    private javax.swing.JLabel TituloTipoTesoroVisiblePerdido;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel muerto;
    private javax.swing.JLabel nivelesPerdidos;
    private javax.swing.JLabel tesorosocultosPerdidos;
    private javax.swing.JLabel tesorosvisiblesPerdidos;
    private javax.swing.JLabel tipotesorosperdidosOcultos;
    private javax.swing.JLabel tipotesorosperdidosVisibles;
    // End of variables declaration//GEN-END:variables
}
